apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-app
  namespace: cpsc-cloud-native
spec:
  selector:
    matchLabels:
      app: demo-app
  namespaceSelector:
    matchNames:
    - cpsc-cloud-native
  endpoints:
  - port: metrics
    interval: 30s
