apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
  namespace: cpsc-cloud-native
data:
  APP_MODE: teaching
  LOG_LEVEL: debug
---
apiVersion: v1
kind: Secret
metadata:
  name: demo-secret
  namespace: cpsc-cloud-native
type: Opaque
stringData:
  DB_PASSWORD: example-password
