apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  namespace: cpsc-cloud-native
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all-by-default
  namespace: cpsc-cloud-native
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
