apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-data
  namespace: cpsc-cloud-native
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo
